Mobileapps 1042
Alfresco/alfresco-mobile-workspace-android pull request #76
Opened 2022-01-25 13:40 UTC by aman-alfresco

- added KB unit for content size and file size

2022-01-25 13:48 UTC, ankitgoyalgloballogic approved these changes

2022-01-27 05:22 UTC, gl-lovekesh requested changes

2022-01-27 05:22 UTC, gl-lovekesh commented on search/src/main/kotlin/com/alfresco/content/search/components/ComponentCreateViewModel.kt
> +private fun String.byteToKB(): String {
Use this function as common for byteToKB.

2022-01-27 07:44 UTC, ankitgoyalgloballogic approved these changes

2022-01-27 07:49 UTC, merged